spring:

  messages:
    basename: i18n/messages/messages
    encoding: UTF-8

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true

#  data:
#    redis:
#      host: localhost
#      port: 6379

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

google:
  apps-script-url: ${GOOGLE_APPS_SCRIPT_URL}
  calendar-id: ${GOOGLE_CALENDAR_ID}
  credentials-json: ${GOOGLE_SERVICE_ACCOUNT_JSON}

#data:
#  GOOGLE_SERVICE_ACCOUNT_JSON: resources/google-service-account.json

sms:
  api-key: ${SMS_API_KEY}
  user: ${SMS_USER}
  password: ${SMS_PASSWORD}
  sender: ${SMS_SENDER}

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework



