version: '3.9'

services:

  postgres:
    image: postgres:17
    container_name: booking-postgres

    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre

    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking-redis
    ports:
      - "6379:6379"