version: '3.9'

services:
  booking-service:
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      TZ: Asia/Jerusalem

  postgres:
    image: postgres:17
    container_name: booking-postgres




    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: booking-redis
    ports:
      - "6379:6379"


